### ISSUE TITLE
java.sql.SQLException: Access denied for user 'root'@'localhost'

### ISSUE THREAD

**Issue by ashutoshsharmaindia** [trK54Ylmz/kafka-spark-streaming-example#3]
Thanks for this post.

Is there any steps for the connection to mysql?
I am running it on ubuntu linux and getting this error:
java.sql.SQLException: Access denied for user 'root'@'localhost'

Went this file:
MySqlConnection
and hard coded the password but still getting the same error.

Do you remember what kind of grant commands or any other commands you ran it to get rid of this error?

**Comment by ashutoshsharmaindia** [comment]
I was able to fix it later. Just went into the config/*.conf directory and provided my credentials there and now it works. Closing the issue now.

**Comment by ashutoshsharmaindia** [comment]
I was able to fix it later. Just went into the config/*.conf directory and provided my credentials there and now it works. Closing the issue now.

**Comment by trK54Ylmz** [comment]
OK. Thanks @ashutoshsharmaindia
