### ISSUE TITLE
dashboard error

### ISSUE THREAD

**Issue by domycapuano** [trK54Ylmz/kafka-spark-streaming-example#4]
![dashboard](https://user-images.githubusercontent.com/25063708/46031387-0484c580-c0f9-11e8-9f08-04872caf4d0c.jpg)
Hi Dear
I followed all the steps but when I connect to the dashboard it is so displayed, what can it be?

thank you

**Comment by trK54Ylmz** [comment]
Hi,

Could you please share the command that you use in the second terminal and JS logs?

You can see the output from developer console.

**Comment by domycapuano** [comment]
![dash_ok](https://user-images.githubusercontent.com/25063708/46074714-ac959f80-c188-11e8-85b6-3b74b128edc8.jpg)
Hi,
thanks for the reply but I think I have solved it
Regards
