### ISSUE TITLE
Spark history 

### ISSUE THREAD

**Issue by Aalnafessah** [trK54Ylmz/kafka-spark-streaming-example#5]
First of all, thanks for such a helpful demo for Spark Streaming.

I the demo is running perfectly with me. I have tried to download the logs for Sparks using Spark History ( https://spark.apache.org/docs/latest/monitoring.html), but I could not find the Spark application within the logs. Is there any way to collect the spark logs from this demo ?

**Comment by trK54Ylmz** [comment]
Sorry for my late reply. 

Do you mean error and output logs? 
Which deployment method did you use for the application? On the YARN or standalone or Kubernetes etc.

You are able to collect the logs and also depends on your deployment method. As far as I know external deployment components are easier than standalone mode.

In YARN, you can see by using Hadoop application history or `yarn logs ...`
In Kubernetes, you can see by using `kubectl ... logs ...`

I haven't use Spark on Mesos.

**Comment by trK54Ylmz** [comment]
I hope you found your answers.

I am closing the issue.
